name: Compatibility Report
description: "Report some other kind of incompatibility with another mod."
labels: [ "Type: Compatibility" ]
body:
  - type: textarea
    attributes:
      label: Description
      description: >
        Please describe the issue in as much detail as possible.
        Explain what happened, and what you expected to have happened instead.
        Include images, screenshots, or videos if applicable.
    validations:
      required: true

  - type: input
    attributes:
      label: Game Log (if applicable)
      description: >
        We may need the game log for additional information.
        This file can be found in the \"logs\" folder of your Minecraft folder as \"latest.log\".
        Please upload the file to https://mclo.gs/ and put the link here.
        **DO NOT** paste the file or its raw here, as that makes it harder to examine, and reduces the chance that we will be able to help you.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Debug Information
      description: >
        Please run the \"/create debuginfo\" command in-game.
        This will copy useful information to your clipboard that will greatly help with debugging.
        Please paste this information here.
        **This is required and needed for debugging, so please don't leave this empty or add something else!**
    validations:
      required: true

  - type: markdown
    attributes:
      value: "Thank you for taking the time to make a report and help improve Create: Sound of Steam!"
