name: Crash Report
description: "Report a crash."
labels: [ "Type: Crash" ]
body:
  - type: textarea
    attributes:
      label: Description
      description: >
        Please describe the crash in as much detail as possible.
        Include images, screenshots, or videos if applicable.
    validations:
      required: true

  - type: input
    attributes:
      label: Crash Report
      description: >
        We may need the crash report for additional information.
        This file can be found in the \"crash-reports\" folder of your Minecraft folder as \"crash-*.txt"\.
        Please upload the file to https://mclo.gs/ and put the link here.
        **DO NOT** paste the file or its raw here, as that makes it harder to examine, and reduces the chance that we will be able to help you.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Debug Information
      description: >
        If possible please run the \"/create debuginfo\" command in-game.
        This will copy useful information to your clipboard that will greatly help with debugging.
        Please paste this information here.
        
        If that is not possible, please shortly describe which version you are using, which addons and on what operating system you are etc.
    validations:
      required: true

  - type: markdown
    attributes:
      value: "Thank you for taking the time to make a report and help improve Create: Sound of Steam!"
